### ISSUE TITLE
[Bug]: Conflict with hodgepodge packet fixes

### ISSUE THREAD

**Issue by Omgise** [GTMEGA/EndlessIDs#181]
### OS

Windows

### GPU

NVIDIA

### Game log

[crash-2024-06-08_10.02.11-client.txt](https://github.com/user-attachments/files/15746126/crash-2024-06-08_10.02.11-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/15746127/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/15746128/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/15746129/latest.log)

### Description

Crashes while starting the game.

**Comment by Omgise** [comment]
After closing the `extendDataWatcher`, the game no longer crashes

**Comment by FalsePattern** [comment]
This is a bug in HodgePodge, disable `validatePacketEncodingBeforeSending` in the hodgepodge config, and you can enable `extendDataWatcher` then.

I have it fixed in the dev branch, so this will be properly fixed in the next update.

**Comment by FalsePattern** [comment]
Should be fixed in 1.5.1

**Comment by Omgise** [comment]
Still crash
[crash-2024-06-10_07.35.22-client.txt](https://github.com/user-attachments/files/15754555/crash-2024-06-10_07.35.22-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/15754556/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/15754557/fml-junk-earlystartup.log)
[latest.log](https://github.com/user-attachments/files/15754558/latest.log)

**Comment by FalsePattern** [comment]
Should be fixed in 1.5.2

**Comment by Omgise** [comment]
It's fixed now, thank!
